name: ams_flutter
description: AMS — BBOTS Management System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2
  http: ^1.6.0
  intl: ^0.20.2
  fl_chart: ^0.70.2
  phone_numbers_parser: ^9.0.21
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
